### ISSUE TITLE
Testing(?)

### ISSUE THREAD

**Issue by michaelachrisco** [freecodecamp-fresnoca/arthop-map-dev#12]
In order for Travis to work, the tests have been disabled from the repo. Should we be doing some basic testing or wait to a later date? What is everyone's thoughts on the matter.

**Comment by edgargdev** [comment]
I think it would be great if we went over writing some tests together. Everyone would benefit from it.

**Comment by michaelachrisco** [comment]
Sounds good. We can go over some basics and get our marker.js(?) tested with mock-able json from firebase (if they dont already have something like that).

**Comment by michaelachrisco** [comment]
Starting on this branch. Is bower going to be removed from the stack entirely? If so, we will have to pull in another testing package (I can think of a few). Ill go over an example.

**Comment by edgargdev** [comment]
Nah bower is needed to handle the angular dependecies. So unless we have npm handle that we need to keep bower.
